Preps for Kubernetes
gznznzjsn/task-service pull request #10
Opened 2023-04-04 11:16 UTC by gznznzjsn

2023-04-04 12:08 UTC, h1alexbel requested changes
@gznznzjsn 
decompose this pr into k8s-related changes and changes related to Serializers and other application logic

2023-04-04 12:08 UTC, h1alexbel commented on .github/workflows/image-push.yml
> +    branches: [ "dev" ]
it's better to run workflows on push and pull-requests in `master` branch

2023-04-05 07:57 UTC, gznznzjsn commented
@h1alexbel everything is done

2023-04-05 09:34 UTC, h1alexbel requested changes

2023-04-05 09:34 UTC, h1alexbel commented on src/main/java/com/gznznzjsn/taskservice/web/kafka/RequirementSender.java
>                          SenderRecord.create(
it's not good to hardcode the message key. Messages with the same key will be sent in one partition

2023-04-05 10:19 UTC, gznznzjsn commented on src/main/java/com/gznznzjsn/taskservice/web/kafka/RequirementSender.java
>                          SenderRecord.create(
Done

2023-04-05 10:51 UTC, h1alexbel approved these changes
OK

2023-04-05 10:51 UTC, merged